### PR TITLE
Fix #49 retrieve scanned urls

### LINKED ISSUE #49: Add the ability to retrieve scanned URLs
To correctly implement diagnostic reporting, we need to have access to the real list of scanned URLs. With this list, the developer can more easily troubleshoot its runtime problems. 

We currently access to the list through reflection on the initContext. A public method (maybe on the initContext) would be an improvement.

### PR DESCRIPTION
**Pull request by pith**
This PR add a `getUrls()` method on `Kernel`.

### CODE REVIEW

**Comment by pith** [comment]
I was also thinking add a `KernelInfo getKernelInfo()` method instead. This `KernelInfo`class would regroup all the info possibly useful for debugging, for instance: 

    Map<String, Plugin> plugins();
    UnitModule unitModule(Class<? extends Plugin> plugin);
    UnitModule overridingUnitModule(Class<? extends Plugin> plugin);
    UnitModule nonGuiceUnitModule(Class<? extends Plugin> plugin);
    UnitModule nonGuiceOverridingUnitModule(Class<? extends Plugin> plugin);
    GlobalModule globalModule();
    Set<URL> scannedURLs();

@ejemba @adrienlauer if you agree with this I will open a new issue for this.

**Comment by adrienlauer** [comment]
I agree with a KernelInfo object. Should reduce clutter.

**Comment by ejemba** [comment]
@pith this looks good to me as well. Reduce the interface surface is always a good thing.
:+1:

**Comment by pith** [comment]
@ejemba Good, I open a new issue for this. Can merge this one ?

**Comment by ejemba** [comment]
@pith Yes you can !

**Pull request merged**
