### PR TITLE
Refactor the installation of Modules and Classes

### PR DESCRIPTION
**Pull request by pith**
Refactor `KernelGuiceModuleInternal` and the computation of concerns.

### CODE REVIEW

**Comment by ejemba** [comment]
@pith can you just explain what you change in substance ?

**Comment by pith** [comment]
Nothing changed concerning the behavior. I didn't touch any tests. But made some simplifications.

* The priority weight have been moved into the `Priority` enum.
* The `Installable` inner class have rename to `Installer` and extracted
* `Installer` no more deal with `Object` but is an abstract class
* I added a `ClassInstaller` for the classes to bind
* I added a `UnitModuleInstaller` for the `UnitModule`s to bind

The new `Installer` abstract class provide two methods to implement:

* order(): return a long computed with the `@Concern` annoation
* install(): install the Class/Module

**Comment by ejemba** [comment]
LGTM ! 
:+1:

**Comment by pith** [comment]
Arf my version of JMockit doesn't compile with openJDK 6 and openJDK 7 ...

**Comment by pith** [comment]
@ejemba @adrienlauer do you think it's worth keeping openjdk6 and openjdk7 in the matrix build ? Having JMockit would be great ...

**Comment by ejemba** [comment]
@pith I do think jdk7 at least is currently always a target. 
I will soon split a version for jdk7 1.X and another for jdk 8 2.X 
(later jdk9 3.X) 
At this time you'll be able to use JMockit on 2.X

**Pull request merged**
